version: '3.7'

volumes:
  postgres:

services:
  app:
    build: .

    depends_on:
      - db

    working_dir: /app
    volumes:
      - .:/app:cached
      - postgres:/var/run/postgresql
      # - gem_data:./usr/local/bundle
    # working_dir: /app

    entrypoint: ./entrypoint.sh
    stdin_open: true
    tty: true

    ports:
      - '3000:3000'

    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      PORT: 3000
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_MAX_THREADS: 2
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: 3035
      # WEBPACKER_DEV_SERVER_INLINE: 'true'

    command: rails s -b 0.0.0.0

  db:
    image: postgres

    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

    volumes:
      - postgres:/var/run/postgresql
      - .:/app:cached

    ports:
      - '5432:5432'
